const novatos = ['Naruto Uzumaki','Sasuke Uchiha','Sakura Haruno','Hinata Hyuuga','Kiba Inuzuka','Shino Aburame','Shikamaru Nara','Ino Yamanaka','Choji Akimichi']
console.log(novatos)
const time7 = novatos.slice(0, 3)
time7.push('Kakashi Hatake')
const time8 = novatos.slice(3, 6)
time8.push('Kurenai Yuri')
const time9 = novatos.slice(6)
time9.push('Asuma Sarutobi')
console.log(`Time 7: ${time7}`)
console.log(`Time 8: ${time8}`)
console.log(`Time 9: ${time9}`)
console.log('\nDepois em Shippuden...\n')
//Substituindo o Sasuke no time 7
//Splice funciona colocando o index inicial e em seguida o numero de valores a serem deletados
time7.splice(1,1,'Sai')
console.log(`Time 7: ${time7}`)
console.log(`Time 8: ${time8}`)
console.log(`Time 9: ${time9}`)
console.log('\nDepois em Boruto...\n')
time7.splice(0,0,'Boruto Uzumaki')
time7.splice(1,1,'Sarada Uchiha')
time7.splice(2,2,'Mitsuki')
time7.splice(3,3,'Konohamaru Sarutobi')
console.log(`Time 7: ${time7}`)